### ISSUE TITLE
Does it work with Hitachi RAS-E13CAK

### ISSUE THREAD

**Issue by loyukfai** [Mixiaoxiao/ESP8266-IR-HOMEKIT#14]
Tried different Hitachi setting but no response.

Thanks.

**Comment by shengweitw** [comment]
https://github.com/crankyoldgit/IRremoteESP8266/blob/master/SupportedProtocols.md

**Comment by loyukfai** [comment]
Thanks! Is there anyway to update the library easily? I bought a pre-built module and currently have no access to an FTDI adapter nor build environment.

Cheers.
